<?php 
$I = new FunctionalTester($scenario);
$I->wantTo('Check member registration');
$I->amOnPage("/member-content");
$I->see('Member sign in');
$I->fillField('_email', 'developer@bogus.info');
$I->click('Sign in');
$I->see('register');
//$I->loginAsAdmin();
//$I->amOnPage("/wp-admin");
//$I->amOnPluginsPage();
//$I->activatePlugin('remote-member-authorization');
//$I->amOnPage("/wp-admin/options-general.php?page=rma-settings");
////$I->see('Remote Member Authentication');
//$I->see('API key');
//$I->selectOption('form input[id=authAPI]', 'API key');
//$I->click('Save stuff');
//$I->see('API key may not be empty');
//$I->see('API key field name may not be empty');
//$I->see('User data URI may not be empty');
//$I->see('Set password URI may not be empty');
//$I->see('Status field name may not be empty');
//$I->see('Active status value may not be empty');